# Generated by Django 5.2.17 on 2026-09-22 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryteamassignment',
            name='qa_tester',
            field=models.ForeignKey(blank=True, help_text="'QA Tester' group-т багтсан (эсвэл superuser) хэрэглэгчид л сонголтод гарна.", limit_choices_to=models.Q(('groups__name', 'QA Tester'), ('is_superuser', True), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categoryteamassignment',
            name='team_lead',
            field=models.ForeignKey(blank=True, help_text="'Project Manager' group-т багтсан (эсвэл superuser) хэрэглэгчид л сонголтод гарна.", limit_choices_to=models.Q(('groups__name', 'Project Manager'), ('is_superuser', True), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
