# Generated by Django 5.2.17 on 2026-09-22 08:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_categoryteamassignment_qa_tester_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Энэ багт харьяалагдах ажилчид. Ticket assign хийхэд зөвхөн эдгээр хэрэглэгчид сонголтод гарна.', limit_choices_to=models.Q(('groups__name', 'Developer'), ('is_superuser', True), _connector='OR'), related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
