# Generated by Django 5.2.17 on 2026-09-24 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_remove_categoryteamassignment_qa_tester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryteamassignment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_assignments', to='categories.category'),
        ),
        migrations.AlterUniqueTogether(
            name='categoryteamassignment',
            unique_together={('category', 'team')},
        ),
    ]
