# Generated by Django 5.2.17 on 2026-09-25 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_category_multiple_teams'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_lead',
            field=models.ForeignKey(blank=True, help_text='Ямар ч идэвхтэй хэрэглэгчийг томилж болно. Team Lead нь өөрийн багийн ticket-ийг оноох, хариуцагч солих, багийн dashboard харах эрхтэй.', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
