# Generated by Django 5.2.17 on 2026-09-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Бага'), ('medium', 'Дунд'), ('high', 'Өндөр'), ('critical', 'Яаралтай')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'Шинэ'), ('assigned', 'Оноогдсон'), ('in_progress', 'Хийгдэж байгаа'), ('resolved', 'Шийдэгдсэн'), ('rejected', 'Татгалзсан'), ('qa_test', 'Чанарын шалгалтад'), ('reopened', 'Дахин нээгдсэн'), ('closed', 'Хаагдсан')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('bug', 'Алдаа (Bug)'), ('task', 'Даалгавар (Task)'), ('cr', 'Өөрчлөлтийн хүсэлт (CR)')], max_length=20),
        ),
    ]
