# Generated by Django 5.2.17 on 2026-09-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_priority_alter_ticket_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sla_due_at',
            field=models.DateTimeField(blank=True, help_text='Priority-с хамаарсан хариу үйлдэл хийх дээд хугацаа (settings.SLA_HOURS_BY_PRIORITY-ээс ticket үүсэх мөчид автоматаар тооцоологдоно).', null=True),
        ),
    ]
