# Generated by Django 5.2.17 on 2026-09-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_sla_due_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_internal',
            field=models.BooleanField(default=False, help_text="Тэмдэглэгдсэн бол зөвхөн дотоод багийн гишүүд харна (Zendesk/Freshdesk-ийн 'Internal note' шиг)."),
        ),
    ]
