# Generated by Django 5.2.17 on 2026-09-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_comment_is_internal'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='first_responded_at',
            field=models.DateTimeField(blank=True, help_text='Ticket-д анх удаа хариу өгсөн (NEW-аас шилжсэн эсвэл мэдээлэгчээс бусад хүн comment бичсэн) огноо.', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='first_response_breach_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='first_response_due_at',
            field=models.DateTimeField(blank=True, help_text="'Time to First Response' SLA — эхний хариу өгөх дээд хугацаа (settings.SLA_FIRST_RESPONSE_HOURS_BY_PRIORITY-ээс автоматаар тооцоологдоно).", null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='first_response_warning_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_breach_notified_at',
            field=models.DateTimeField(blank=True, help_text='SLA хугацаа хэтэрсэн тухай escalation мэдэгдэл илгээсэн огноо (check_sla_deadlines командаар бичигдэнэ, давхар мэдэгдэл илгээхээс сэргийлнэ).', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_warning_sent_at',
            field=models.DateTimeField(blank=True, help_text='SLA хугацаа дуусахад ойртсон тухай анхааруулга илгээсэн огноо (check_sla_deadlines командаар бичигдэнэ, давхар мэдэгдэл илгээхээс сэргийлнэ).', null=True),
        ),
    ]
