# Generated by Django 5.2.17 on 2026-09-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_first_responded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, help_text="Ticket дээр сүүлд ямар нэгэн идэвх (status шилжилт, comment, attachment) гарсан огноо — 'идэвхгүй ticket' automation-д ашиглагдана.", null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='stale_reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='Идэвхгүй байдлын тухай сүүлд сануулга илгээсэн огноо (check_stale_tickets командаар бичигдэнэ). Шинэ идэвх гарахад цэвэрлэгдэж, дараагийн удаа дахин сануулах боломжтой болно.', null=True),
        ),
    ]
