# Generated by Django 5.2.17 on 2026-09-25 06:39

import apps.tickets.storage
from django.db import migrations, models


def move_existing_files(apps, schema_editor):
    """Өмнө нь нийтэд нээлттэй media/attachments-д байсан файлуудыг private_media руу зөөнө."""
    import shutil
    from pathlib import Path

    from django.conf import settings

    source = Path(settings.MEDIA_ROOT) / "attachments"
    if not source.is_dir():
        return
    target = Path(settings.PRIVATE_MEDIA_ROOT) / "attachments"
    for path in source.rglob("*"):
        if path.is_file():
            destination = target / path.relative_to(source)
            destination.parent.mkdir(parents=True, exist_ok=True)
            if destination.exists():
                continue
            try:
                shutil.move(str(path), str(destination))
            except OSError:
                # Эх файлыг устгах эрхгүй бол (жишээ нь docker-оор root үүсгэсэн)
                # хуулна — хуучин хуулбарыг гараар устгана уу.
                try:
                    shutil.copy2(str(path), str(destination))
                except OSError as exc:
                    print(f"  ! {path} зөөж чадсангүй: {exc}")


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_last_activity_at_and_more'),
    ]

    operations = [
        migrations.RunPython(move_existing_files, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(storage=apps.tickets.storage.private_storage, upload_to='attachments/%Y/%m/'),
        ),
    ]
