# Generated by Django 5.2.17 on 2026-09-25 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_attachment_private_storage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('duplicates', 'давхардсан'), ('blocks', 'хааж байна'), ('relates', 'холбоотой'), ('parent_of', 'дэд даалгавартай')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_out', to='tickets.ticket')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_in', to='tickets.ticket')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('source', 'target', 'link_type'), name='unique_ticket_link'), models.CheckConstraint(condition=models.Q(('source', models.F('target')), _negated=True), name='ticket_link_not_self')],
            },
        ),
    ]
