# Generated by Django 5.2.17 on 2026-09-25 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_watchers_and_notifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
