# Generated by Django 5.2.17 on 2026-09-25 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_delete_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='watchers',
        ),
        migrations.DeleteModel(
            name='TicketLink',
        ),
    ]
