# Generated by Django 5.2.17 on 2026-09-28 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_subcategory'),
        ('tickets', '0011_remove_watchers_and_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='categories.subcategory'),
        ),
    ]
