# Generated by Django 5.2.17 on 2026-09-28 08:35

import apps.tickets.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('tickets', '0012_ticket_subcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Нэр')),
                ('file', models.FileField(storage=apps.tickets.storage.private_storage, upload_to='autotest/data/%Y/%m/')),
                ('columns', models.JSONField(default=list)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_data_files', to='projects.project')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PageScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=600)),
                ('status', models.CharField(choices=[('queued', 'Дараалалд'), ('done', 'Дууссан'), ('failed', 'Алдаатай')], default='queued', max_length=10)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Нэр')),
                ('description', models.TextField(blank=True, verbose_name='Тайлбар')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_apps', to='projects.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Жишээ: Бүртгүүлэх, Нэвтрэх', max_length=150, verbose_name='Нэр')),
                ('page_path', models.CharField(help_text='Орчны үндсэн хаягаас хойших зам. Жишээ: /register', max_length=500, verbose_name='Хуудас')),
                ('fields', models.JSONField(default=list)),
                ('submit_selector', models.CharField(blank=True, max_length=500)),
                ('submit_label', models.CharField(blank=True, max_length=200)),
                ('success_mode', models.CharField(choices=[('auto', 'Автоматаар (хуудас шилжсэн, алдааны мессеж гараагүй)'), ('url_contains', 'Хаяг (URL) нь дараах текстийг агуулсан'), ('text_visible', 'Хуудсанд дараах текст гарсан')], default='auto', max_length=20, verbose_name='Амжилттай гэж үзэх нөхцөл')),
                ('success_value', models.CharField(blank=True, max_length=300, verbose_name='Нөхцөлийн текст')),
                ('error_selector', models.CharField(blank=True, help_text='Хоосон бол түгээмэл алдааны элементүүдийг (.error, [role=alert] ...) автоматаар хайна.', max_length=300, verbose_name='Алдааны мессежийн элемент')),
                ('expected_column', models.CharField(blank=True, help_text="'амжилттай' / 'алдаа' эсвэл 'алдаа: мессеж' гэж бичсэн багана. Хоосон бол зөвхөн тэмдэглэнэ.", max_length=150, verbose_name='Хүлээгдэх үр дүнгийн багана')),
                ('expected_message_column', models.CharField(blank=True, max_length=150, verbose_name='Хүлээгдэх мессежийн багана')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='autotest.testapp')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Жишээ: dev, staging', max_length=50, verbose_name='Орчин')),
                ('base_url', models.URLField(help_text='Жишээ: https://staging.shop.mn', verbose_name='Үндсэн хаяг')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='autotest.testapp')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_file_name', models.CharField(max_length=150)),
                ('environment_name', models.CharField(max_length=50)),
                ('target_url', models.URLField(max_length=600)),
                ('status', models.CharField(choices=[('queued', 'Дараалалд'), ('running', 'Ажиллаж байна'), ('done', 'Дууссан'), ('failed', 'Алдаатай зогссон'), ('cancelled', 'Цуцлагдсан')], default='queued', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total', models.PositiveIntegerField(default=0)),
                ('passed', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('errored', models.PositiveIntegerField(default=0)),
                ('recorded', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('data_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='autotest.datafile')),
                ('environment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='autotest.environment')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='autotest.scenario')),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RunResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=300)),
                ('input_data', models.JSONField(default=dict)),
                ('expected_outcome', models.CharField(blank=True, choices=[('success', 'амжилттай'), ('error', 'алдаа'), ('unknown', 'тодорхойгүй')], max_length=10)),
                ('expected_message', models.TextField(blank=True)),
                ('actual_outcome', models.CharField(blank=True, choices=[('success', 'амжилттай'), ('error', 'алдаа'), ('unknown', 'тодорхойгүй')], max_length=10)),
                ('actual_message', models.TextField(blank=True)),
                ('final_url', models.URLField(blank=True, max_length=1000)),
                ('verdict', models.CharField(choices=[('pass', 'Тэнцсэн'), ('fail', 'Унасан'), ('error', 'Ажиллуулж чадсангүй'), ('recorded', 'Тэмдэглэсэн')], max_length=10)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('screenshot', models.FileField(blank=True, storage=apps.tickets.storage.private_storage, upload_to='autotest/shots/%Y/%m/')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autotest_results', to='tickets.ticket')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='autotest.testrun')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='testapp',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='autotest_unique_app_name'),
        ),
        migrations.AddConstraint(
            model_name='environment',
            constraint=models.UniqueConstraint(fields=('app', 'name'), name='autotest_unique_env_name'),
        ),
    ]
