# Generated by Django 5.2.17 on 2026-09-29 03:56

import apps.autotest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='base_url',
            field=models.CharField(help_text='Жишээ: https://staging.shop.mn', max_length=200, validators=[apps.autotest.models.validate_base_url], verbose_name='Үндсэн хаяг'),
        ),
    ]
