# Generated by Django 5.2.17 on 2026-09-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotest', '0002_environment_base_url_single_label_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runresult',
            name='verdict',
            field=models.CharField(choices=[('pass', 'Тэнцсэн'), ('fail', 'Унасан'), ('error', 'Ажиллуулж чадсангүй'), ('recorded', 'Гараар шалгах')], max_length=10),
        ),
    ]
