# Generated by Django 5.2.17 on 2026-09-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotest', '0003_verdict_review_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='page_path',
            field=models.CharField(blank=True, help_text='Орчны хаягаас хойших зам. Хоосон бол орчны хаягийг шууд нээнэ.', max_length=500, verbose_name='Хуудас'),
        ),
    ]
