# Generated by Django 5.2.17 on 2026-09-30 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotest', '0006_category_and_pages_finalize'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagescan',
            name='login_url',
            field=models.URLField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='testapp',
            name='login_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='autotest.page', verbose_name='Нэвтрэх хуудас'),
        ),
        migrations.AddField(
            model_name='testrun',
            name='account_label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='testrun',
            name='login_url',
            field=models.URLField(blank=True, max_length=600),
        ),
        migrations.CreateModel(
            name='TestAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Жишээ: QA, Admin', max_length=50, verbose_name='Нэр')),
                ('username', models.CharField(max_length=150, verbose_name='Нэвтрэх нэр')),
                ('password_encrypted', models.TextField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='autotest.testapp')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.AddField(
            model_name='pagescan',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='autotest.testaccount'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='scenarios', to='autotest.testaccount', verbose_name='Хэн болж шалгах'),
        ),
        migrations.AddField(
            model_name='testrun',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='autotest.testaccount'),
        ),
        migrations.AddConstraint(
            model_name='testaccount',
            constraint=models.UniqueConstraint(fields=('app', 'label'), name='autotest_unique_account_label'),
        ),
    ]
