# Generated by Django 5.2.17 on 2026-09-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotest', '0007_test_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='access_rules',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='testrun',
            name='access_rules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='testrun',
            name='kind',
            field=models.CharField(choices=[('data', 'Өгөгдлөөр'), ('access', 'Эрх шалгах')], default='data', max_length=10),
        ),
        migrations.AlterField(
            model_name='runresult',
            name='actual_outcome',
            field=models.CharField(blank=True, choices=[('success', 'амжилттай'), ('error', 'алдаа'), ('unknown', 'тодорхойгүй'), ('open', 'нээлттэй'), ('denied', 'хаалттай')], max_length=10),
        ),
        migrations.AlterField(
            model_name='runresult',
            name='expected_outcome',
            field=models.CharField(blank=True, choices=[('success', 'амжилттай'), ('error', 'алдаа'), ('unknown', 'тодорхойгүй'), ('open', 'нээлттэй'), ('denied', 'хаалттай')], max_length=10),
        ),
    ]
