# Generated by Django 5.2.17 on 2026-10-02 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotest', '0008_access_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='runresult',
            name='response_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='api_body',
            field=models.TextField(blank=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='api_headers',
            field=models.TextField(blank=True, verbose_name='Header'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='api_method',
            field=models.CharField(default='POST', max_length=10, verbose_name='Method'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='api_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='Зам'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='kind',
            field=models.CharField(choices=[('web', 'Веб форм'), ('api', 'API')], default='web', max_length=10),
        ),
        migrations.AddField(
            model_name='testapp',
            name='api_login_body',
            field=models.TextField(blank=True, default='{"username": "{{username}}", "password": "{{password}}"}', verbose_name='API нэвтрэх body'),
        ),
        migrations.AddField(
            model_name='testapp',
            name='api_login_path',
            field=models.CharField(blank=True, help_text='Жишээ: /api/auth/login/', max_length=500, verbose_name='API нэвтрэх зам'),
        ),
        migrations.AddField(
            model_name='testapp',
            name='api_token_prefix',
            field=models.CharField(blank=True, default='Bearer', max_length=30, verbose_name='Token-ий угтвар'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='scenarios', to='autotest.page', verbose_name='Хуудас'),
        ),
    ]
