# Generated by Django 5.2.17 on 2026-10-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotest', '0009_api_scenarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='is_production',
            field=models.BooleanField(default=False, verbose_name='Production'),
        ),
    ]
